# Generated by Django 4.2.30 on 2026-06-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
