# Generated by Django 6.0.4 on 2026-05-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
