# Generated by Django 4.2.30 on 2026-06-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pseudonym',
        ),
    ]
